name: flutter_be
description: Reverse method call, null safe, robust.
version: 1.0.1
homepage: https://github.com/Meterwhite/flutter_be
documentation: https://github.com/Meterwhite/flutter_be

environment:
  sdk: ">=2.12.0 <=3.5.4"

dependencies:
  # flutter:
  #   sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
