name: flutter_be
description: "Reverse Method Call Using `?` Operator: Simplifies null-safe method calls, making your code cleaner and more robust."
version: 2.0.0
homepage: https://github.com/Meterwhite/flutter_be
documentation: https://github.com/Meterwhite/flutter_be

environment:
  sdk: ">=2.12.0 <4.0.0"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
